bracketSpacing: true
endOfLine: "auto"
importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
importOrderParserPlugins: ["typescript"]
importOrderSeparation: true
importOrderSortSpecifiers: true
printWidth: 100
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: "all"
